### ISSUE TITLE
Recreating Squash with Traceability to Task and PR in Commit Message Integration Strategy, without Any Commits in the Branch Referencing the Task 

### ISSUE THREAD

**Issue by nik-esh** [nik-esh/CS471WorkflowsHomeworkAssignment#12]
References user story #1

## TODO:
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `task-12_squash_preferred_project_workflow_recreated`
- [x] Edit the description of the PR to reference this task
- [x] In the PR, use the `Squash and merge` option to integrate the changes into `master` and the commit message should be `Closes #12  (#<ID_PR>)`, and remove the extended description in the commit
- [ ] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
